// Generated by CoffeeScript 1.7.1
(function() {
  App.register("{{id}}", function(params, scope, widgets) {
    var $container;
    $container = scope.$id(params['containerId']);
    return {
      show: function() {
        return $container.modal('show');
      }
    };
  });

}).call(this);

//# sourceMappingURL=window.map
